forum_app/urls.py
from django.urls import path
from forum_app import views

urlpatterns = [
    path('chapters', views.ForumChaptersView.as_view(), name="forum_chapters"),
    path('chapter/<slug:chapter_slug>/topics', views.ForumTopicsView.as_view(), name="forum_topics"),
    path('chapter/<slug:chapter_slug>/create-topic', views.ForumCreateTopicView.as_view(), name="forum_create_topic"),
    path('chapter/<slug:chapter_slug>/topic/<slug:topic_slug>', views.ForumMessagesView.as_view(), name="forum_messages"),
    path('chapter/<slug:chapter_slug>/topic/<slug:topic_slug>/create-message', 
         views.ForumCreateMessageView.as_view(), name="forum_create_message"),
    
]

seo/urls.py
from django.urls import path
from seo import views

urlpatterns = [
    path('init-sitemap-file', views.init_sitemap_file, name="init-sitemap"),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_app.urls')),
    path('forum/', include('forum_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('seo/', include('seo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum_app/models.py
import uuid
from django.db import models

from site_app.models import User


class Chapter(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    logo = models.ImageField(upload_to="chapter_uploads/", null=True, blank=True)
    title = models.CharField(max_length=255, default="", null=True)
    slug = models.SlugField(unique=True, max_length=500)

    def __str__(self):
        return self.title


class Topic(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255, default="", null=True)
    slug = models.SlugField(unique=True, max_length=500)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="topic_creator")
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, related_name="topic_chapter")

    def __str__(self):
        return self.title
    

class Message(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    body = models.TextField(default="", null=True, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="message_creator")
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, related_name="message_chapter")
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="message_topic")

    def __str__(self):
        return self.creator.username


class MessageFile(models.Model):
    FILE_TYPE = (
        ("image", "Image",),
        ("video", "Video",),
        ("document", "Document",),
        ("file", "File",),
    )
    created = models.DateTimeField(auto_now_add=True)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    file = models.FileField(upload_to='forum_uploads/', null=True, blank=True)
    file_type = models.CharField(max_length=255, choices=FILE_TYPE, default="file")
    name = models.CharField(max_length=255, null=True, blank=True)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="message_file_obj")
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="message_file_topic", null=True)
    

forum_app/forms.py
from django import forms
from forum_app.models import Topic, Message
from ckeditor.widgets import CKEditorWidget


class NewMessageForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget(config_name='public'), required=True)
    class Meta:
        model = Message
        fields = ("body",)
	
    def __init__(self, *args, **kwargs):
        super(NewMessageForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

forum_app/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from forum_app.models import Chapter, MessageFile, Topic, Message
from forum_app.forms import NewMessageForm


class ForumCreateMessageView(LoginRequiredMixin, View):
    template_view = 'forum_app/forum_create_message.html'
    login_url = reverse_lazy('login')

    def get(self, request, chapter_slug, topic_slug):
        try:
            chapter = Chapter.objects.get(slug=chapter_slug)
            topic = Topic.objects.get(slug=topic_slug)
            form = NewMessageForm()
            return render(request, self.template_view, context={
                "title": f"RadioCircuit | Create message",
                "topic": topic,
                "chapter": chapter,
                "form": form,
            })
        except (Chapter.DoesNotExist, Topic.DoesNotExist):
            raise Http404()
    
    def post(self, request, chapter_slug, topic_slug):
        try:
            chapter = Chapter.objects.get(slug=chapter_slug)
            topic = Topic.objects.get(slug=topic_slug)
            form = NewMessageForm()
            if not request.POST.get("body", None):
                return render(request, self.template_view, context={
                    "title": f"RadioCircuit | Create message",
                    "topic": topic,
                    "chapter": chapter,
                    "form": form,
                    "error": "Message body is required."
                })
            message = Message.objects.create(
                body=request.POST.get("body", ""),
                creator=request.user,
                chapter=chapter,
                topic=topic
            )
            for key, file in request.FILES.items():
                file_type = "file"
                if key.startswith("img"):
                    file_type = "image" 
                MessageFile.objects.create(
                    file=file,
                    file_type=file_type,
                    name=str(file),
                    message=message,
                    topic=topic
                )
            return redirect(reverse("forum_messages", args=(chapter_slug, topic_slug)))
        except (Chapter.DoesNotExist, Topic.DoesNotExist):
            raise Http404()


class ForumCreateTopicView(LoginRequiredMixin, View):
    template_view = 'forum_app/forum_create_topic.html'
    login_url = reverse_lazy('login')

    def get(self, request, chapter_slug):
        chapter = get_object_or_404(Chapter, slug=chapter_slug)
        return render(request, self.template_view, context={
            "title": f"RadioCircuit | Create topic"
        })
    
    def post(self, request, chapter_slug):
        chapter = get_object_or_404(Chapter, slug=chapter_slug)
        topics_count = Topic.objects.all().count()
        topic = Topic.objects.create(
            title=request.POST.get('title'),
            slug=slugify(f"{request.POST.get('title')}__{str(topics_count+1)}"),
            creator=request.user,
            chapter=chapter
        )
        return redirect(reverse("forum_messages", args=(chapter_slug, topic.slug,))+"?page=1&result=success")


class ForumMessagesView(View):
    template_view = 'forum_app/forum_messages.html'

    def get(self, request, chapter_slug, topic_slug):
        try:
            chapter = Chapter.objects.get(slug=chapter_slug)
            topic = Topic.objects.get(slug=topic_slug)
            instances = Message.objects.filter(chapter=chapter, topic=topic).order_by('created')
            paginator = Paginator(instances, 15)
            page_number = request.GET.get("page", 1)
            page_obj = paginator.get_page(page_number)
            page_obj.adjusted_elided_pages = paginator.get_elided_page_range(page_number)
            get_params = dict()
            for k, v in request.GET.items():
                get_params[k] = v
            get_params.pop("page", None)
            instances = page_obj.object_list
            if 'page' not in request.GET:
                return redirect(reverse("forum_messages", args=(chapter.slug, topic.slug))+f"?page={paginator.num_pages}")
            return render(request, self.template_view, context={
                "title": f"RadioCircuit | Messages",
                "messages": instances,
                "topic": topic,
                "chapter": chapter,
                "page_obj": page_obj,
                "get_params": get_params,
            })
        except (Chapter.DoesNotExist, Topic.DoesNotExist):
            raise Http404()


class ForumTopicsView(View):
    template_view = 'forum_app/forum_topics.html'

    def get(self, request, chapter_slug):
        try:
            chapter = Chapter.objects.get(slug=chapter_slug)
            instances = Topic.objects.filter(chapter=chapter).order_by('-created')
            paginator = Paginator(instances, 15)
            page_number = request.GET.get("page", 1)
            page_obj = paginator.get_page(page_number)
            page_obj.adjusted_elided_pages = paginator.get_elided_page_range(page_number)
            get_params = dict()
            for k, v in request.GET.items():
                get_params[k] = v
            get_params.pop("page", None)
            instances = page_obj.object_list
            return render(request, self.template_view, context={
                "title": f"RadioCircuit | Topics",
                "topics": instances,
                "chapter": chapter,
                "page_obj": page_obj,
                "get_params": get_params,
            })
        except Chapter.DoesNotExist:
            raise Http404()


class ForumChaptersView(View):
    template_view = 'forum_app/forum_chapters.html'

    def get(self, request):
        chapters = Chapter.objects.all()
        return render(request, self.template_view, context={
            "title": f"RadioCircuit | Chapters",
            "chapters": chapters
        })

forum_app/templates/forum_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="icon" type="image/x-icon" href="/favicon.ico">
        <title>{{title}}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        {% block custom_css %}{% endblock %}
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-PPL89XB5Q8"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-PPL89XB5Q8');
        </script>
    </head>
    <body class="bg-light">
        {% include 'navbar.html' %}
        {% include 'header.html' %}
        
        <div class="container" style="min-height:65vh;">
            {% block content %}{% endblock %}
        </div>

        {% include 'footer.html' %}
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block custom_js %}{% endblock %}
    </body>
</html>

forum_app/templates/forum_app/forum_chapters.html
{% extends 'forum_app/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <table class="table table-borderless align-middle">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Title</th>
                    <th scope="col">Topics</th>
                    <th scope="col">Messages</th>
                    <th scope="col">Last activity</th>
                  </tr>
                </thead>
                <tbody>
                    {% for chapter in chapters %}
                        <tr class="my-1">
                            <th class="" width="50px">
                                <img width="30px" src="{% if chapter.logo %}{{chapter.logo.url}}{%else%}{% static 'svg/chapter.svg' %}{%endif%}" alt="">
                            </th>
                            <td class="">
                                <a href="{% url 'forum_topics' chapter.slug %}" class="text-decoration-none h5 text-primary-emphasis">{{chapter.title}}</a>
                            </td>
                            <td>{{chapter.topic_chapter.all.count}}</td>
                            <td>{{chapter.message_chapter.all.count}}</td>
                            <td>
                                <p class="m-0" style="font-size: 12px;" >Author: <b>{{chapter.message_chapter.all.last.creator.username}}</b></p>
                                <p class="m-0" style="font-size: 12px;" >Topic: <b>{{chapter.message_chapter.all.last.topic.title}}</b></p>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

forum_app/templates/forum_app/forum_create_message.html
{% extends 'forum_app/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-8 col-sm-12">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if error %}
                    <div class="alert alert-danger mb-3">{{error}}</div>
                {% endif %}
                <div class="mb-3">
                  <label for="id_body" class="form-label">Message body</label>
                  {{form.body}}
                </div>
                <hr>
                <p class="h5">Add image</p>
                <div class="d-flex flex-wrap align-middle" id="image-wrap">
                    <div class="m-3 nm-file-input">
                        <input class="form-control form-control-sm" name="img_1" type="file">
                    </div>
                </div>
                <button class="btn btn-success" id="add_image_btn" ><b>+</b></button>
                <hr>
                <p class="h5">Add file</p>
                <div class="d-flex flex-wrap" id="file-wrap">
                    <div class="m-3 nm-file-input">
                        <input class="form-control form-control-sm" name="file_1" type="file">
                    </div>
                </div>
                <button class="btn btn-success" id="add_file_btn"><b>+</b></button>
                <hr>
                <button type="submit" class="btn btn-primary" >Send message</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_js %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script type="text/javascript" src="{% static "js/new_message.js" %}"></script>
{% endblock %}

forum_app/templates/forum_app/forum_create_topic.html
{% extends 'forum_app/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <form action="" method="post">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="title" class="form-label">Create new topic</label>
                  <input type="text" name="title" maxlength="100" class="form-control" id="title" placeholder="Title" required>
                  <div id="title" class="form-text">Max length of title - 100 words</div>
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

forum_app/templates/forum_app/forum_messages.html
{% extends 'forum_app/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <a class="text-primary text-decoration-none" href="{% url 'forum_chapters' %}">Chapters</a>
            <span>/</span>
            <a class="text-primary text-decoration-none" href="{% url 'forum_topics' chapter.slug %}">{{chapter.title}}</a>
            <span>/</span>
            <a class="text-black text-decoration-none">{{topic.title}}</a>
        </div>
        {% if request.user.is_authenticated %}
        <div class="col-12">
            <a class="btn btn-success {% if request.GET.result == 'success' %}pulse{%endif%}"
            href="{% url 'forum_create_message' chapter.slug topic.slug %}">+ Message</a>
        </div>
        {% endif %}
    </div>
    <hr>
    {% for message in messages %}
        <div class="row my-2">
            <!-- <div class="col-12 empty-line p-1 bg-primary bg-opacity-50" ></div> -->
            <div class="col-3 border border-2">
                <div class="row">
                    <div class="col-12 text-center my-1">
                        {% if message.creator.avatar %}
                            <img src="{{message.creator.avatar.url}}" class="w-100 rounded-circle" style="max-width: 150px;" alt="Avatar" />
                        {% else %}
                            <img src="{% static 'svg/person.svg' %}" class="w-100 rounded-circle" style="max-width: 150px;" alt="Avatar" />
                        {% endif %}
                    </div>
                    <div class="col-12">
                        <p class="text-center"><b>{{message.creator.username}}</b></p>
                        <!-- <p class="text-center text-muted m-0 " style="font-size: 13px;">
                            <span title="Date joined" class="badge" style="background-color: blueviolet;">{{message.creator.date_joined}}</span>
                        </p> -->
                        <p class="text-center text-muted m-0" style="font-size: 13px;">Messages: <span class="badge bg-success">{{message.creator.message_creator.all.count}}</span></p>
                        <p class="text-center text-muted" style="font-size: 13px;">Rang: <span class="badge bg-danger">{{message.creator.rang}}</span></p>
                    </div>
                </div>
            </div>
            <div class="col-9 border border-2">
                <div class="row">
                    <div class="col">
                        <span class="badge bg-warning text-black">{{message.created}}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col my-2">
                        {{message.body|safe}}
                    </div>
                </div>
                <div class="d-flex flex-wrap">
                    {% for file in message.message_file_obj.all %}
                        {% if file.file_type == "image" %}
                            <a class="attach-img m-2 p-1" href="{{file.file.url}}" target="_blank">
                                <div class="attach-forum" style="background-image: url('{{file.file.url}}');"></div>
                                <p class="m-0">{{file.name}}</p>
                            </a>
                        {% endif %}
                        {% if file.file_type == "file" %}
                            <a class="attach-file m-2 p-1" href="{{file.file.url}}" download>
                                <div class="attach-forum d-flex justify-content-center">
                                    <img width="50px" src="{% static 'svg/file.svg' %}" alt="">
                                </div>
                                <p class="m-0">{{file.name}}</p>
                            </a>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <!-- <div class="col-12 empty-line p-1 bg-primary bg-opacity-50" ></div> -->
        </div>
    {% endfor %}
    {% if messages %}
    <div class="row">
      <div class="col">
        {% include 'pagination.html' %}
      </div>
    </div>
    {% endif %}
    <hr>

    {% if request.user.is_authenticated %}
    <div class="row">
        <div class="col-12">
            <a class="btn btn-success {% if request.GET.result == 'success' %}pulse{%endif%}"
            href="{% url 'forum_create_message' chapter.slug topic.slug %}">+ Message</a>
        </div>
    </div>
    {% endif %}

</div>
{% endblock %}

forum_app/templates/forum_app/forum_topics.html
{% extends 'forum_app/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <a class="text-primary text-decoration-none" href="{% url 'forum_chapters' %}">Chapters</a>
            <span>/</span>
            <a class="text-black text-decoration-none">{{chapter.title}}</a>
        </div>
        {% if request.user.is_authenticated %}
        <div class="col-12">
            <a class="btn btn-success" href="{% url 'forum_create_topic' chapter.slug %}">+ Topic</a>
        </div>
        {% endif %}
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <table class="table table-borderless align-middle">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Title</th>
                    <th scope="col">Messages</th>
                    <th scope="col">Last activity</th>
                  </tr>
                </thead>
                <tbody>
                    {% for topic in topics %}
                        <tr class="my-1">
                            <th class="" width="50px">
                                <img width="25px" src="{% static 'svg/topic.svg' %}" alt="">
                            </th>
                            <td class="">
                                <a href="{% url 'forum_messages' chapter.slug topic.slug %}" class="text-decoration-none h5 text-primary-emphasis">{{topic.title}}</a>
                            </td>
                            <td>{{topic.message_topic.all.count}}</td>
                            <td>
                                <p class="m-0" style="font-size: 12px;" >Author: <b>{{topic.message_topic.all.last.creator.username}}</b></p>
                                <p class="m-0" style="font-size: 12px;" >Created: <b>{{topic.message_topic.all.last.created}}</b></p>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if topics %}
    <div class="row">
      <div class="col">
        {% include 'pagination.html' %}
      </div>
    </div>
    {% endif %}
</div>
{% endblock %}